spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${ANGICO_DB_URL}
    username: ${ANGICO_DB_USER}
    password: ${ANGICO_DB_PASSWORD}
  servlet:
    multipart:
      max-request-size: ${ANGICO_UPLOAD_MAX_REQUEST_SIZE:4MB}
  jpa:
    hibernate:
      ddl-auto: update

angico:
  database:
    migrations-enabled: ${ANGICO_FLYWAY_ENABLED:true}
  auth:
    cookie-secure: true
  allowed-origins: ${ANGICO_ALLOWED_ORIGINS}
