CREATE TABLE acao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    missao_id VARCHAR(255),
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000),
    status VARCHAR(255) NOT NULL,
    responsavel_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    workspace_id VARCHAR(255),
    token_hash VARCHAR(64) NOT NULL,
    csrf_token_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_auth_session_token_hash UNIQUE (token_hash)
);

CREATE TABLE conversa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    territorio_id BIGINT,
    context_entity_type VARCHAR(255),
    context_entity_id VARCHAR(255),
    titulo VARCHAR(240),
    status VARCHAR(255),
    created_by_pessoa_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE evidencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    subject_type VARCHAR(40),
    subject_id BIGINT,
    title VARCHAR(200),
    description VARCHAR(2000),
    original_filename VARCHAR(180),
    content_type VARCHAR(100),
    size_bytes BIGINT,
    sha256 VARCHAR(64),
    storage_path VARCHAR(1000),
    captured_at TIMESTAMP WITH TIME ZONE,
    recorded_at TIMESTAMP WITH TIME ZONE,
    actor_id VARCHAR(255),
    device_id VARCHAR(128),
    client_mutation_id VARCHAR(128),
    CONSTRAINT uk_evidencia_workspace_client_mutation
        UNIQUE (workspace_id, client_mutation_id)
);

CREATE TABLE idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    operation_kind VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    resource_type VARCHAR(80),
    resource_id VARCHAR(255),
    response_status INTEGER,
    response_content_type VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_idempotency_scope
        UNIQUE (workspace_id, actor_id, operation_kind, idempotency_key)
);

CREATE TABLE indicador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    territorio_id BIGINT,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    unidade VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE medicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    indicador_id BIGINT,
    valor DOUBLE PRECISION,
    unidade VARCHAR(255),
    fonte VARCHAR(255),
    measured_at TIMESTAMP WITH TIME ZONE,
    actor_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE memory_event (
    sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    workspace_id VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255) NOT NULL,
    entity_version BIGINT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE,
    actor_id VARCHAR(255),
    source VARCHAR(255) NOT NULL,
    schema_version INTEGER NOT NULL,
    correlation_id VARCHAR(255),
    causation_id VARCHAR(255),
    idempotency_key VARCHAR(255),
    device_id VARCHAR(255),
    sync_status VARCHAR(255),
    organization_id VARCHAR(255),
    payload_json OID
);

CREATE TABLE memory_object (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    status VARCHAR(255),
    source VARCHAR(255),
    external_code VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_object_identity UNIQUE (workspace_id, entity_type, entity_id)
);

CREATE TABLE memory_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    origin_type VARCHAR(255) NOT NULL,
    origin_id VARCHAR(255) NOT NULL,
    relation_type VARCHAR(255) NOT NULL,
    destination_type VARCHAR(255) NOT NULL,
    destination_id VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    confidence NUMERIC(5, 4),
    active_identity VARCHAR(64),
    actor_id VARCHAR(255),
    source VARCHAR(255),
    notes VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_memory_relation_active_identity UNIQUE (active_identity)
);

CREATE TABLE mensagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    conversa_id BIGINT,
    sender_pessoa_id BIGINT,
    sender_nome VARCHAR(255),
    corpo VARCHAR(4000),
    status VARCHAR(255),
    linked_entity_type VARCHAR(255),
    linked_entity_id VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    local_descricao VARCHAR(500),
    client_message_id VARCHAR(128),
    device_id VARCHAR(128),
    occurred_at TIMESTAMP WITH TIME ZONE,
    recorded_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_mensagem_workspace_client_message
        UNIQUE (workspace_id, sender_pessoa_id, client_message_id)
);

CREATE TABLE mensagem_anexo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    mensagem_id BIGINT,
    attachment_type VARCHAR(255),
    original_filename VARCHAR(260),
    content_type VARCHAR(255),
    storage_path VARCHAR(1000),
    size_bytes BIGINT,
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE message_read_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    conversa_id BIGINT NOT NULL,
    pessoa_id BIGINT NOT NULL,
    last_read_message_id BIGINT,
    read_through TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_message_read_receipt_conversation_person
        UNIQUE (workspace_id, conversa_id, pessoa_id)
);

CREATE TABLE missao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    territorio_id VARCHAR(255),
    problema_id VARCHAR(255),
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000),
    status VARCHAR(255) NOT NULL,
    responsavel_id VARCHAR(255),
    progresso INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE observacao_territorial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    territorio_id VARCHAR(255),
    titulo VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000),
    localizacao VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    cidade VARCHAR(255),
    estado VARCHAR(255),
    bairro VARCHAR(255),
    urgencia VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    autor_id VARCHAR(255),
    client_mutation_id VARCHAR(128),
    occurred_at TIMESTAMP WITH TIME ZONE,
    device_id VARCHAR(128),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_observacao_workspace_client_mutation
        UNIQUE (workspace_id, client_mutation_id)
);

CREATE TABLE organizacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    nome VARCHAR(200),
    tipo VARCHAR(40),
    status VARCHAR(20),
    mission_id BIGINT,
    mission_relation VARCHAR(20),
    actor_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE participacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    organization_id BIGINT,
    pessoa_id BIGINT,
    papel VARCHAR(40),
    status VARCHAR(20),
    started_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE,
    recorded_at TIMESTAMP WITH TIME ZONE,
    actor_id VARCHAR(255),
    active_identity VARCHAR(64),
    CONSTRAINT uk_participacao_active_identity UNIQUE (active_identity)
);

CREATE TABLE pessoa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    telefone VARCHAR(255),
    foto OID,
    papel VARCHAR(255),
    status VARCHAR(255),
    angico_id VARCHAR(255),
    password_hash VARCHAR(255),
    auth_token_hash VARCHAR(255),
    auth_token_issued_at TIMESTAMP WITH TIME ZONE,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE potencialidade_territorial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    territorio_id VARCHAR(255),
    titulo VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000),
    localizacao VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(255) NOT NULL,
    autor_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE problema_socioambiental (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    territorio_id VARCHAR(255),
    origem_observacao_id VARCHAR(255),
    titulo VARCHAR(255) NOT NULL,
    categoria VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000),
    severidade VARCHAR(255) NOT NULL,
    localizacao VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    status VARCHAR(255) NOT NULL,
    autor_id VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE recurso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    categoria VARCHAR(40) NOT NULL,
    unidade VARCHAR(40) NOT NULL,
    descricao VARCHAR(2000),
    status VARCHAR(20) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE resultado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    acao_id BIGINT,
    titulo VARCHAR(200),
    descricao VARCHAR(2000),
    status VARCHAR(255),
    actor_id VARCHAR(255),
    occurred_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE territorio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    nome VARCHAR(255),
    tipo VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(255),
    bairro VARCHAR(255),
    pais VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    bounding_box VARCHAR(255),
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE uso_recurso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    recurso_id BIGINT NOT NULL,
    acao_id BIGINT NOT NULL,
    quantidade NUMERIC(16, 4) NOT NULL,
    unidade VARCHAR(40) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_id VARCHAR(255) NOT NULL
);

CREATE TABLE workspace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    status VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(255),
    center_latitude DOUBLE PRECISION,
    center_longitude DOUBLE PRECISION,
    created_by VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_workspace_slug UNIQUE (slug)
);

CREATE TABLE workspace_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_member_workspace_actor UNIQUE (workspace_id, actor_id)
);

ALTER TABLE auth_session
    ADD CONSTRAINT fk_auth_session_pessoa
    FOREIGN KEY (pessoa_id) REFERENCES pessoa (id);

CREATE UNIQUE INDEX uk_pessoa_email_normalized
    ON pessoa (LOWER(BTRIM(email)))
    WHERE email IS NOT NULL AND BTRIM(email) <> '';
CREATE UNIQUE INDEX uk_pessoa_angico_id_normalized
    ON pessoa (LOWER(REGEXP_REPLACE(BTRIM(angico_id), '^@', '')))
    WHERE angico_id IS NOT NULL AND BTRIM(angico_id) <> '';
CREATE INDEX idx_event_workspace
    ON memory_event (workspace_id);
CREATE INDEX idx_event_entity
    ON memory_event (workspace_id, entity_type, entity_id);
CREATE INDEX idx_relation_origin
    ON memory_relation (workspace_id, origin_type, origin_id, relation_type, active);
