package com.angico.common;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;
import java.util.UUID;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;

class IdentityMigrationTest {

    @Test
    void migratesLegacySchemaWithoutLosingRowsAndEnforcesNormalizedIdentityUniqueness() throws Exception {
        String url = "jdbc:h2:mem:legacy-" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "");
                var statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE pessoa (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email VARCHAR(255),
                        angico_id VARCHAR(255)
                    )
                    """);
            statement.execute("INSERT INTO pessoa (email, angico_id) VALUES "
                    + "('legacy@example.test', 'legacy.id')");
        }

        Flyway.configure()
                .dataSource(url, "sa", "")
                .locations("classpath:db/migration/common", "classpath:db/migration/h2")
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("0"))
                .cleanDisabled(true)
                .load()
                .migrate();

        try (var connection = DriverManager.getConnection(url, "sa", "");
                var statement = connection.createStatement()) {
            assertEquals(1, scalar(statement,
                    "SELECT COUNT(*) FROM pessoa WHERE email = 'legacy@example.test'"));
            assertEquals(List.of("0", "1", "2"), versions(statement));
            assertTrue(scalar(statement,
                    "SELECT COUNT(*) FROM information_schema.tables "
                            + "WHERE table_name = 'AUTH_SESSION'") > 0);
            assertTrue(scalar(statement,
                    "SELECT COUNT(*) FROM information_schema.table_constraints "
                            + "WHERE constraint_name = 'FK_AUTH_SESSION_PESSOA'") > 0);

            assertThrows(SQLException.class, () -> statement.execute(
                    "INSERT INTO pessoa (email, angico_id) VALUES "
                            + "('LEGACY@example.test', 'different.id')"));
            assertThrows(SQLException.class, () -> statement.execute(
                    "INSERT INTO pessoa (email, angico_id) VALUES "
                            + "('different@example.test', 'LEGACY.ID')"));
        }
    }

    private int scalar(java.sql.Statement statement, String sql) throws SQLException {
        try (var result = statement.executeQuery(sql)) {
            result.next();
            return result.getInt(1);
        }
    }

    private List<String> versions(java.sql.Statement statement) throws SQLException {
        try (var result = statement.executeQuery(
                "SELECT \"version\" FROM \"flyway_schema_history\" "
                        + "WHERE \"success\" = TRUE AND \"version\" IS NOT NULL "
                        + "ORDER BY \"installed_rank\"")) {
            var versions = new java.util.ArrayList<String>();
            while (result.next()) {
                versions.add(result.getString(1));
            }
            return versions;
        }
    }
}
