-- Apply only after checking the duplicate queries below return no rows.
-- SELECT lower(email), count(*) FROM pessoa WHERE email IS NOT NULL AND btrim(email) <> '' GROUP BY lower(email) HAVING count(*) > 1;
-- SELECT lower(angico_id), count(*) FROM pessoa WHERE angico_id IS NOT NULL AND btrim(angico_id) <> '' GROUP BY lower(angico_id) HAVING count(*) > 1;

CREATE TABLE IF NOT EXISTS auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    workspace_id VARCHAR(255),
    token_hash VARCHAR(64) NOT NULL,
    csrf_token_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_auth_session_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_auth_session_token_hash
    ON auth_session (token_hash);
CREATE INDEX IF NOT EXISTS idx_auth_session_pessoa
    ON auth_session (pessoa_id);
CREATE INDEX IF NOT EXISTS idx_auth_session_expires
    ON auth_session (expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_pessoa_email_normalized
    ON pessoa (lower(email))
    WHERE email IS NOT NULL AND btrim(email) <> '';
CREATE UNIQUE INDEX IF NOT EXISTS uk_pessoa_angico_id_normalized
    ON pessoa (lower(angico_id))
    WHERE angico_id IS NOT NULL AND btrim(angico_id) <> '';
