CREATE TABLE IF NOT EXISTS auth_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    workspace_id VARCHAR(255),
    token_hash VARCHAR(64) NOT NULL,
    csrf_token_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_auth_session_token_hash
    ON auth_session (token_hash);
CREATE INDEX IF NOT EXISTS idx_auth_session_pessoa
    ON auth_session (pessoa_id);
CREATE INDEX IF NOT EXISTS idx_auth_session_expires
    ON auth_session (expires_at);
