CREATE TABLE IF NOT EXISTS idempotency_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    operation_kind VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    resource_type VARCHAR(80),
    resource_id VARCHAR(255),
    response_status INTEGER,
    response_content_type VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_idempotency_scope
    ON idempotency_record (workspace_id, actor_id, operation_kind, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_idempotency_resource
    ON idempotency_record (workspace_id, resource_type, resource_id);

ALTER TABLE IF EXISTS observacao_territorial
    ADD COLUMN IF NOT EXISTS client_mutation_id VARCHAR(128);
ALTER TABLE IF EXISTS observacao_territorial
    ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS observacao_territorial
    ADD COLUMN IF NOT EXISTS device_id VARCHAR(128);

CREATE UNIQUE INDEX IF NOT EXISTS uk_observacao_workspace_client_mutation
    ON observacao_territorial (workspace_id, client_mutation_id);
