CREATE TABLE IF NOT EXISTS evidencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS resultado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    acao_id BIGINT,
    titulo VARCHAR(200),
    descricao VARCHAR(2000),
    status VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS organizacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    nome VARCHAR(200),
    tipo VARCHAR(40),
    status VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS participacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(255);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS subject_type VARCHAR(40);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS subject_id BIGINT;
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS title VARCHAR(200);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS description VARCHAR(2000);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS original_filename VARCHAR(180);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS content_type VARCHAR(100);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS size_bytes BIGINT;
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS sha256 VARCHAR(64);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS storage_path VARCHAR(1000);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS captured_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS actor_id VARCHAR(255);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS device_id VARCHAR(128);
ALTER TABLE IF EXISTS evidencia ADD COLUMN IF NOT EXISTS client_mutation_id VARCHAR(128);

CREATE UNIQUE INDEX IF NOT EXISTS uk_evidencia_workspace_client_mutation
    ON evidencia (workspace_id, client_mutation_id);
CREATE INDEX IF NOT EXISTS idx_evidencia_workspace_subject
    ON evidencia (workspace_id, subject_type, subject_id);

ALTER TABLE IF EXISTS resultado ADD COLUMN IF NOT EXISTS actor_id VARCHAR(255);
ALTER TABLE IF EXISTS resultado ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMP WITH TIME ZONE;
CREATE INDEX IF NOT EXISTS idx_resultado_workspace_action
    ON resultado (workspace_id, acao_id);

ALTER TABLE IF EXISTS organizacao ADD COLUMN IF NOT EXISTS mission_id BIGINT;
ALTER TABLE IF EXISTS organizacao ADD COLUMN IF NOT EXISTS mission_relation VARCHAR(20);
ALTER TABLE IF EXISTS organizacao ADD COLUMN IF NOT EXISTS actor_id VARCHAR(255);
CREATE INDEX IF NOT EXISTS idx_organizacao_workspace
    ON organizacao (workspace_id);

ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(255);
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS pessoa_id BIGINT;
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS papel VARCHAR(40);
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS status VARCHAR(20);
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS started_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS ended_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS actor_id VARCHAR(255);
ALTER TABLE IF EXISTS participacao ADD COLUMN IF NOT EXISTS active_identity VARCHAR(64);

CREATE UNIQUE INDEX IF NOT EXISTS uk_participacao_active_identity
    ON participacao (active_identity);
CREATE INDEX IF NOT EXISTS idx_participacao_workspace_organization
    ON participacao (workspace_id, organization_id, started_at);

CREATE TABLE IF NOT EXISTS recurso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    nome VARCHAR(200) NOT NULL,
    categoria VARCHAR(40) NOT NULL,
    unidade VARCHAR(40) NOT NULL,
    descricao VARCHAR(2000),
    status VARCHAR(20) NOT NULL,
    actor_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_recurso_workspace_nome
    ON recurso (workspace_id, nome);

CREATE TABLE IF NOT EXISTS uso_recurso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    recurso_id BIGINT NOT NULL,
    acao_id BIGINT NOT NULL,
    quantidade NUMERIC(16, 4) NOT NULL,
    unidade VARCHAR(40) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    actor_id VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_uso_recurso_workspace_resource
    ON uso_recurso (workspace_id, recurso_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_uso_recurso_workspace_action
    ON uso_recurso (workspace_id, acao_id);
