CREATE TABLE IF NOT EXISTS conversa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    territorio_id BIGINT
);

ALTER TABLE IF EXISTS conversa ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(255);
ALTER TABLE IF EXISTS conversa ADD COLUMN IF NOT EXISTS territorio_id BIGINT;
ALTER TABLE IF EXISTS conversa ADD COLUMN IF NOT EXISTS context_entity_type VARCHAR(255);
ALTER TABLE IF EXISTS conversa ADD COLUMN IF NOT EXISTS context_entity_id VARCHAR(255);

UPDATE conversa
SET context_entity_type = 'TERRITORIO',
    context_entity_id = CAST(territorio_id AS VARCHAR)
WHERE context_entity_type IS NULL
  AND territorio_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_conversa_workspace_context
    ON conversa (workspace_id, context_entity_type, context_entity_id);

CREATE TABLE IF NOT EXISTS mensagem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255),
    conversa_id BIGINT,
    sender_pessoa_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE IF EXISTS mensagem ADD COLUMN IF NOT EXISTS workspace_id VARCHAR(255);
ALTER TABLE IF EXISTS mensagem ADD COLUMN IF NOT EXISTS conversa_id BIGINT;
ALTER TABLE IF EXISTS mensagem ADD COLUMN IF NOT EXISTS sender_pessoa_id BIGINT;
ALTER TABLE IF EXISTS mensagem ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS mensagem ADD COLUMN IF NOT EXISTS client_message_id VARCHAR(128);
ALTER TABLE IF EXISTS mensagem ADD COLUMN IF NOT EXISTS device_id VARCHAR(128);
ALTER TABLE IF EXISTS mensagem ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS mensagem ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMP WITH TIME ZONE;

UPDATE mensagem SET occurred_at = created_at WHERE occurred_at IS NULL;
UPDATE mensagem SET recorded_at = created_at WHERE recorded_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_mensagem_workspace_client_message
    ON mensagem (workspace_id, sender_pessoa_id, client_message_id);
CREATE INDEX IF NOT EXISTS idx_mensagem_conversation_occurred
    ON mensagem (conversa_id, occurred_at, id);

CREATE TABLE IF NOT EXISTS message_read_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id VARCHAR(255) NOT NULL,
    conversa_id BIGINT NOT NULL,
    pessoa_id BIGINT NOT NULL,
    last_read_message_id BIGINT,
    read_through TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_message_read_receipt_conversation_person
    ON message_read_receipt (workspace_id, conversa_id, pessoa_id);
CREATE INDEX IF NOT EXISTS idx_message_read_receipt_lookup
    ON message_read_receipt (workspace_id, conversa_id, pessoa_id);
